# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af4c07d1affa6e302f2067ef3006c270650eb1ebd8bacdddc5229637707a22638d874bf20fbb7f00a757fee25b5fecd3e1bd2a0cbe0fb40c4344fb26bbc2117c

test:
  secret_key_base: a11cdc0adc7f7ce07f2596382bb4df53f75c7a05031f5d518a6d40c319f5da45bb5d9b44369dc5d7f9915e7995e0a01098afda950d16c44db5d2f0b4cb2cc2ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
